language: java
jdk: openjdk8
after_success:
- mvn coveralls:report
env:
  global:
    secure: u1FCEI7fAC77wJP3UTCQ/2bJemzjxQ4OB5WpcWTqomkwd6VFGX4YxX7LlBfb68g/egJapa9erdEIAqJnolg5qEdWHtRCLpm5AzdIJuWnaj2oXIG5CRngAa64K7wpyI6+LpAYVN5kFe4uXBN6HHOCVjjpQ/fIUFhzMb3oPVnHrD4lBBniNh5pTwO5J4j/DwFsmemlXVi1rMbt1llR+FwJU8pZrhx0HnhYiummQNuyvmoumjt7w/bUM10zYB7D30I+MDFOTabUfFqUc3PJYeP78iE8zkWgw7rEQrvusaEqilFoa3vJg+vMK99cIZXumgGDCMT9K9hiWmqc93Ifvk/G2b5qgDiYXcjFCMxgerygaxGmFqYRbs0Ssgz2nwXXRJULfJy/w7lqkeOhd1hEFCSx5Td4wWYwedRc8RtJe+ot8R0C4IJETZxTliMtLlfNEvMd/LNozLd51a7fK6QXJ/0Fik3LlU54467n9eoH4+leHzAgy3dz/HHuZ2CBIKufXDEnXY4fSKQrL/qeAkDLMEINRBDS03bAo7ko98p79n3iAWvIb1BYtZ3DSU1QgR6Tm8IryjJULUfpxDrd8adqXKdPwI5DIJr9e60JEeUlr0aVj19Gs3HpG6AnnSlLy8atwSIijSGaEhv7kGvMT437kpbhsRiZmzpkB+knPdEJUBCqXD4=
